name: Run Advent of Code Solutions

on:
  push:
    branches:
      - master

jobs:
  run_solutions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 
      - name: Run Solutions
        run: |
          for folder in $(find . -maxdepth 1 -type d -name "day_*_*" -printf "%p\n" | sort); do
            echo "Running solutions in $folder"
            cd "$folder"
            cargo run -q
            echo ""
            echo ""
            cd ..
          done
